CREATE TABLE IF NOT EXISTS REPORT (
    report_id varchar(36) NOT NULL,
    login_id varchar(36) NOT NULL,
    type_id int NOT NULL,
    place_id int NOT NULL,
    repair_id int NULL,
    state_id int NOT NULL DEFAULT 0,
    report_dt TIMESTAMP NOT NULL,
    is_time_not_match boolean DEFAULT false,
    description_notify text NULL,
    image_file text NULL,
    description VARCHAR(255) NULL,
    create_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_success boolean DEFAULT false,
    is_allow boolean DEFAULT false,
    item_price int NULL,
    active boolean DEFAULT false,
    PRIMARY KEY (report_id),
    FOREIGN KEY (login_id) REFERENCES USER_INFO(login_id),
    FOREIGN KEY (type_id) REFERENCES SELECT_PLACE_TYPE(type_id),
    FOREIGN KEY (place_id) REFERENCES SELECT_PLACE(place_id),
    FOREIGN KEY (repair_id) REFERENCES SELECT_ITEM_REPAIR(repair_id),
    FOREIGN KEY (state_id) REFERENCES REPORT_STATE(state_id)) DEFAULT CHARSET= utf8;