CREATE TABLE IF NOT EXISTS SELECT_PLACE_TYPE (
    type_id int NOT NULL ,
    type_name VARCHAR(255) NOT NULL,
    active boolean DEFAULT false,
    create_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (type_id)) DEFAULT CHARSET= utf8;